### PR TITLE
Added founded_at field to body, closes help-513

### PR DESCRIPTION
**Pull request by blacksph3re**

### CODE REVIEW

**Comment by blacksph3re** [comment]
it's on prod

**Comment by serge1peshcoff** [comment]
awesome, then it's only frontend changes left. will do tonight

**Comment by serge1peshcoff** [comment]
@blacksph3re one more question: do you need global permission to edit or or the local is enough?

**Comment by blacksph3re** [comment]
local is enough

**Comment by serge1peshcoff** [comment]
should it be like this? I thought only ND or somebody from admins should be able to edit it.

**Comment by serge1peshcoff** [comment]
will ask Evrim

**Pull request merged**
