### PR TITLE
Separate fee payments

### PR DESCRIPTION
**Pull request by blacksph3re**
This creates an API for fee payments as we discussed it in slack. Expiry information on body memberships is currently not solved with a virtual boolean but a normal one which should increase GET performance.

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
is it working for bodies and for locals the same way?

**Comment by blacksph3re** [comment]
Yes currently it's the same with bodies and locals. We can create an attribute on the body which automatically sets all members to unexpired if that's needed

**Comment by serge1peshcoff** [comment]
What I suggest is to do it based on the body type, for 'contact', 'contact antenna' and 'antenna' it can be as it is, for other the membership should be always not expired. What do you think?

**Comment by serge1peshcoff** [comment]
for Academy probably not, I don't know, better ask Alejandra. But will we ever need that flexibility? I suggest doing it as simple as possible and later refactor if needed

**Comment by serge1peshcoff** [comment]
and for academy, it's not represented as a local but as 'partner' instead

**Comment by blacksph3re** [comment]
Actually it's not much more work to introduce that boolean while it seems cleaner to me. Hardcoding that would rule out any other association from being able to use the system (not that this is a high-priority aim at the moment) and I kind of liked this question as a validation to the flexibility of the system.

**Comment by serge1peshcoff** [comment]
yeah, but it'd be too much work of changing these booleans in case something changes. For example, for now every body is an antenna in the database so they'd all have to be changes to the appropriate ones after migrating

**Comment by blacksph3re** [comment]
It's one SQL statement, actually it's in the migration and we can just run it when we want to change them all at once

**Comment by blacksph3re** [comment]
I have added your idea uncommented, maybe we can put that on the list to ask matis

**Comment by serge1peshcoff** [comment]
anyway we need to wait before all of the bodies in the system would be updated for the corresponding body type. I've asked Evrim already to take care of it

**Pull request merged**
