### PR TITLE
fix: do not recompile when we launch the app

### PR DESCRIPTION
**Pull request by linuxbandit**
Please test on local you too please

### CODE REVIEW

**Comment by linuxbandit** [comment]
should make it such that on container startup there is no overhead caused by re-compilation of stuff.

Compilation happens on container build, migrations on container startup (see bootstrap.sh)

**Comment by serge1peshcoff** [comment]
I'm pretty sure it's `--no-compile`

**Comment by serge1peshcoff** [comment]
also doesn't seem nice that my checks passed, while the application didn't start. need to update it somehow

**Comment by linuxbandit** [comment]
when you say "my" you mean circleCI I guess?

**Comment by serge1peshcoff** [comment]
and also seems like it compiles again, wtf.
I've also faced it when trying to run the app locally, but thought it was something with my setup, apparently not.

**Comment by serge1peshcoff** [comment]
@linuxbandit answering your questions, yes

**Comment by linuxbandit** [comment]
does it work "smooth" for you when you reload the service on your local machine? i.e. what is the overhead on startup?

if that works fine, it means that we have not set the pipeline to do the right commands (e.g. do we use the development version -> do we build everytime?)

**Comment by serge1peshcoff** [comment]
can't test it in the container now, can do in the evening most likely

**Comment by linuxbandit** [comment]
bump @serge1peshcoff

**Comment by serge1peshcoff** [comment]
I assume this can be closed? @linuxbandit

**Comment by linuxbandit** [comment]
the whole project could be archived, yes

**Pull request closed without merging**
