### PR TITLE
Made type field in bodies mandatory and an enum-like thing 

### PR DESCRIPTION
**Pull request by blacksph3re**
the type field is now mandatory and can only be one of some predefined values. Instead of creating a database default I figured it would be easier doing a manual SQL query which changes all unset body types to antenna in the production system. That way we are in control if something goes wrong

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
I think adding a NOT NULL constraint on the type field on body can be a good idea, what do you think?

**Comment by blacksph3re** [comment]
Would break our database at the moment. I would first make sure all bodies in the production system actually have a type...
However we could also delay this PR until we did that...

**Comment by serge1peshcoff** [comment]
what about having NOT NULL constraint with DEFAULT field on it? adding NOT NULL constraint without DEFAULT anyway will crash all of the migrations where there's at least 1 body in the system

**Comment by serge1peshcoff** [comment]
okay, I've implemented the frontend changes.
I suggest making a migration when we add the NOT NULL constraint and before that, updating all bodies to have the type 'antenna', what do you think?

**Comment by serge1peshcoff** [comment]
@linuxbandit do you think the `project` should be added as well? (for bodies like EoT)? or how it should be represented in a system?

**Comment by serge1peshcoff** [comment]
@blacksph3re can you add to the allowed values 'partner' and 'project' as well?

**Comment by serge1peshcoff** [comment]
yay, that's super nice now.
@blacksph3re one thing before merging: can you in the migration file change all of the bodies' types to 'antenna' (since it's the most popular) and then add NOT NULL constraint without DEFAULT? would be super lovely

**Comment by serge1peshcoff** [comment]
okay, cool for me, we can merge :D

**Comment by serge1peshcoff** [comment]
I love it, you can merge and deploy it @blacksph3re and then we can ask Alejandra or someone from CD to set the types for bodies existing in the system already.

**Pull request merged**
