### PR TITLE
feat(general): Healthcheck endpoint

### PR DESCRIPTION
**Pull request by blacksph3re**

### CODE REVIEW

**Comment by linuxbandit** [comment]
Brilliant, thanks !

**Comment by serge1peshcoff** [comment]
I'll do the same for statutory, events and discounts on this week. @linuxbandit do you think we need that for frontend? since it's static

**Comment by linuxbandit** [comment]
Did you receive my reply, @serge1peshcoff ? I sent it with email and idk if it went privately to you (i thought it replied to the thread but i dont see it here)

**Comment by serge1peshcoff** [comment]
@linuxbandit this one or some other one?

**Pull request merged**
