### PR TITLE
feat: standardise passwords; improve deployability

### PR DESCRIPTION
**Pull request by linuxbandit**
Changes:

- The default password is 5ecr3t, as we decided being the default for everything 
- The .env file is used both because it's good practice AND to provide more customisation for the bootstrap of the environment (there's still room for improvement)
- Add restart policies for containers
- Add default network
- Remove legacy container
- (WiP) remove HostRegexp as a condition

### CODE REVIEW

**Comment by linuxbandit** [comment]
It is part of a series of PRs, you'll see on oms-docker

**Comment by blacksph3re** [comment]
Looks good. I don't know if changing the password to something else we publish on github will change security in any form, I'd rather read it from secrets...?

**Comment by linuxbandit** [comment]
@blacksph3re can you approve and merge then?

**Comment by linuxbandit** [comment]
the default pw is to know what to try first, plus if we try a default password during the security check we know that we did something wrong

**Comment by blacksph3re** [comment]
I won't merge it yet, as rolling it out to production would break connection to the DB

**Comment by blacksph3re** [comment]
We should schedule a downtime somewhen after agora for that

**Comment by linuxbandit** [comment]
superseded

**Pull request closed without merging**
