### PR TITLE
Optional motivation

### PR DESCRIPTION
**Pull request by blacksph3re**
Motivation to join-requests and campaign submissions is now optional.

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@blacksph3re can you deploy this today? then I can make it optional in frontend as well, should be as simple as adding 2 lines of code

**Comment by blacksph3re** [comment]
yes, I can :) I will just wait for the travis tests

**Comment by blacksph3re** [comment]
okay it's online

**Comment by serge1peshcoff** [comment]
awesome, I'll deploy frontend changes in 10'

**Comment by serge1peshcoff** [comment]
@blacksph3re working as expected, thanks a lot ;)

**Comment by blacksph3re** [comment]
lightspeed deployment :D

**Pull request merged**
